name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write  # Required if you want to allow auto-fixing and pushing changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest ruff mypy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint and fix with Ruff
        run: ruff check --fix .

      - name: Format with Ruff
        run: ruff format .

      - name: Type-check with mypy
        run: mypy . --pretty --extra-checks --ignore-missing-imports

      - name: Test with pytest
        run: pytest tests
